apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediobot-deployment
  labels: 
    app: mediobot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mediobot
  template:
    metadata:
      labels:
        app: mediobot
    spec:
      containers:
      - name: mediobot
        image: agaetisit/mediobot:latest
        env:
        - name: FLICKR_API_KEY
          valueFrom:
            secretKeyRef:
              name: flickr-api
              key: flickr.api.key
        - name: FLICKR_API_SECRET
          valueFrom:
            secretKeyRef:
              name: flickr-api
              key: flickr.api.secret
        - name: spring.data.mongodb.username
          value: mediobot-admin
        - name: spring.data.mongodb.password
          valueFrom:
            secretKeyRef:
              name: mongo
              key: mongodb-password
        resources:
          limits:
            memory: 512M
          requests:
            memory: 512M
---
apiVersion: v1
kind: Service
metadata:
  name: mediobot-service
spec:
  type: LoadBalancer
  selector:
    app: mediobot
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mediobot-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/issuer: mediobot-issuer-prod
spec:
  tls:
  - hosts:
    - mediobot.monobot.fr
    secretName: mediobot-certificate-prod
  rules:
  - host: mediobot.monobot.fr
    http:
      paths:
      - path: /
        backend:
          serviceName: mediobot-service
          servicePort: 80
