apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediobot-deployment
  labels:
    app: mediobot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediobot
  template:
    metadata:
      labels:
        app: mediobot
    spec:
      containers:
      - name: mediobot
        image: agaetisit/mediobot:latest
        env:
        - name: FLICKR_API_KEY
          valueFrom:
            secretKeyRef:
              name: flickr-api
              key: flickr.api.key
        - name: FLICKR_API_SECRET
          valueFrom:
            secretKeyRef:
              name: flickr-api
              key: flickr.api.secret
        - name: spring.data.mongodb.username
          value: mediobot-admin
        - name: spring.data.mongodb.password
          valueFrom:
            secretKeyRef:
              name: mongo
              key: mongodb-password
        - name: detectobot.baseurl
          value: http://detectobot-service.monobot-prod
        - name: detectobot.version
          value: v0.1
        - name: flickr.maxPicturesPerGroup
          value: "200"
        #- name: logging.level.fr.agaetis
        #  value: DEBUG
        resources:
          limits:
            memory: 512M
          requests:
            memory: 512M
        volumeMounts:
          - mountPath: "/pictures"
            name: picturestorage
      volumes:
        - name: picturestorage
          persistentVolumeClaim:
            claimName: pictures-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: mediobot-service
spec:
  type: LoadBalancer
  selector:
    app: mediobot
  ports:
  - port: 80
    targetPort: 8080
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mediobot-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - mediobot.monobot.fr
    secretName: mediobot-certificate-prod-tls
  rules :
  - host: mediobot.monobot.fr
    http:
      paths:
      - path: /
        backend:
          serviceName: mediobot-service
          servicePort: 80
---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: retrieve-media-pictures-job
spec:
  schedule: "0 1 * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: retrieve-media-pictures-job
        spec:
          containers:
            - name: retrieve-media-pictures-job
              image: buildpack-deps:curl
              args:
              - /bin/sh
              - -ec
              - curl -X POST https://mediobot.monobot.fr/picture/media/retrieve
          restartPolicy: Never
---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: trigger-pictures-detection-job
spec:
  schedule: "0 3 * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: trigger-pictures-detection-job
        spec:
          containers:
            - name: trigger-pictures-detection-job
              image: buildpack-deps:curl
              args:
              - /bin/sh
              - -ec
              - curl -X POST https://mediobot.monobot.fr/picture/detection/trigger
          restartPolicy: Never
