apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: webobot-certificate-prod
spec:
  secretName: webobot-certificate-prod
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - monobot-ingress.eastus.cloudapp.azure.com
  acme:
    config:
    - http01:
        ingress: monobot.fr
      domains:
      - monobot.fr
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webobot-deployment
  labels:
    app: webobot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webobot
  template:
    metadata:
      labels:
        app: webobot
    spec:
      containers:
      - name: webobot
        image: agaetisit/webobot:latest
        resources:
          limits:
            memory: 512M
          requests:
            memory: 512M
---

apiVersion: v1
kind: Service
metadata:
  name: webobot-service
spec:
  type: LoadBalancer
  selector:
    app: webobot
  ports:
  - port: 80
    targetPort: 5000
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webobot-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - monobot.fr
    secretName: webobot-certificate-prod
  rules:
  - host: monobot.fr
    http:
      paths:
      - path: /
        backend:
          serviceName: webobot-service
          servicePort: 80
