apiVersion: apps/v1
kind: Deployment
metadata:
  name: webobot-deployment
  labels:
    app: webobot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webobot
  template:
    metadata:
      labels:
        app: webobot
    spec:
      containers:
      - name: webobot
        image: agaetisit/webobot:latest
        resources:
          limits:
            memory: 512M
          requests:
            memory: 256M
---

apiVersion: v1
kind: Service
metadata:
  name: webobot-service
spec:
  type: LoadBalancer
  selector:
    app: webobot
  ports:
  - port: 80
    targetPort: 3000
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: webobot-virtualservice
spec:
  gateways:
  - monobot-gateway
  hosts:
  - monobot.fr
  http:
  - route:
    - destination:
        host: webobot-service
        port:
          number: 80