apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: webobot-certificate-prod
spec:
  secretName: webobot-certificate-prod
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - monobot-ingress.eastus.cloudapp.azure.com
  acme:
    config:
    - http01:
        ingress: monobot.fr
      domains:
      - monobot.fr