apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: detectobot-certificate-prod
spec:
  secretName: detectobot-certificate-prod
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - monobot-ingress.eastus.cloudapp.azure.com
  acme:
    config:
    - http01:
        ingress: detectobot.monobot.fr
      domains:
      - detectobot.monobot.fr
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: detectobot-deployment
  labels:
    app: detectobot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: detectobot
  template:
    metadata:
      labels:
        app: detectobot
    spec:
      containers:
      - name: detectobot
        image: agaetisit/detectobot:latest
        volumeMounts:
          - mountPath: "/input"
            name: picturestorage
      volumes:
        - name: picturestorage
          persistentVolumeClaim:
            claimName: picturestorage-pvc
---

apiVersion: v1
kind: Service
metadata:
  name: detectobot-service
spec:
  type: LoadBalancer
  selector:
    app: detectobot
  ports:
  - port: 80
    targetPort: 5000
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: detectobot-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - detectobot.monobot.fr
    secretName: detectobot-certificate-prod
  rules:
  - host: detectobot.monobot.fr
    http:
      paths:
      - path: /
        backend:
          serviceName: detectobot-service
          servicePort: 80