apiVersion: apps/v1
kind: Deployment
metadata:
  name: detectobot-deployment
  labels:
    app: detectobot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: detectobot
  template:
    metadata:
      labels:
        app: detectobot
    spec:
      containers:
      - name: detectobot
        image: agaetisit/detectobot:latest
        resources:
          limits:
            memory: 2G
          requests:
            memory: 2G
        volumeMounts:
          - mountPath: "/input"
            name: picturestorage
      volumes:
        - name: picturestorage
          persistentVolumeClaim:
            claimName: pictures-pvc
---

apiVersion: v1
kind: Service
metadata:
  name: detectobot-service
spec:
  type: LoadBalancer
  selector:
    app: detectobot
  ports:
  - port: 80
    targetPort: 5000