apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediobot-deployment
  labels: 
    app: mediobot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mediobot
  template:
    metadata:
      labels:
        app: mediobot
    spec:
      containers:
      - name: mediobot
        image: agaetisit/mediobot:latest
        env:
        - name: FLICKR_API_KEY
          valueFrom:
            secretKeyRef:
              name: flickr-api
              key: flickr.api.key.txt
        - name: FLICKR_API_SECRET
          valueFrom:
            secretKeyRef:
              name: flickr-api
              key: flickr.api.secret.txt
        resources:
          limits:
            memory: 512M
          requests:
            memory: 512M
---
apiVersion: v1
kind: Service
metadata:
  name: mediobot-service
spec:
  type: LoadBalancer
  selector:
    app: mediobot
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mediobot-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules: 
  - host: monobot.fr
    http:
      paths:
      - path: /api
        backend:
          serviceName: mediobot-service
          servicePort: 80
